### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [viktak/gps-tracker#2]
Hello!

I found link to this project from https://hackaday.com/2020/11/28/open-hardware-gps-tracker-works-on-your-terms/

Could you please add information about license of this repository — is it allowed to copy, change and use code in any purpose?
It would be great to see any popular open source license.

**Comment by viktak** [comment]
Just added. Thank you

**Comment by vazhnov** [comment]
GPL v3 — great!
Thank you very much!
